import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const style = StyleSheet.create({
  backgroundImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  authWindowContainer: {
    backgroundColor: colors.backgroundMain,
    gap: 16,
    width: '100%',
    minHeight: '55%',
    maxHeight: '85%',
    position: 'absolute',
    bottom: 0,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 32,
    paddingHorizontal: 16,
  },
  registrationWindow: {
    width: '100%',
    height: '100%',
    bottom: 0,
    overflow: 'scroll',
  },
  registrationTitle: {
    fontSize: 30,
    fontWeight: 500,
    width: '100%',
    textAlign: 'center',
    marginBottom: 32,
  },
  loginTitle: {
    fontSize: 30,
    fontWeight: 500,
    width: '100%',
    textAlign: 'center',
    marginBottom: 16,
  },
  avatarContainer: {
    position: 'absolute',
    width: 120,
    height: 120,
    left: '50%',
    transform: 'translateX("-50%"), translateY("-70px")',
    display: 'block',
    overflow: 'hidden',
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 16,
    zIndex: 1,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  textInput: {
    height: 50,
    width: '90%',
    borderWidth: 1,
    borderRadius: 8,
    borderColor: colors.input.default.border,
    padding: 15,
    marginHorizontal: 'auto',
    marginBottom: 16,
  },
  showPassText: {
    position: 'absolute',
    right: 0,
    bottom: 0,
  },
  mainButton: {
    height: 50,
    width: '90%',
    backgroundColor: colors.button.default.background,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    padding: 15,
    marginHorizontal: 'auto',
    marginTop: 43,
  },
  mainButtonText: {
    color: colors.button.default.text,
    fontSize: 16,
    fontWeight: 400,
  },
  redirectText: {
    width: '100%',
    alignItems: 'center',
    color: colors.text.default,
    marginVertical: 16,
  },
});
